title: "Arian Designs"
description: "Modern Clean Blog + Portfolio"
baseurl: ""
url: "https://ariantechzone-stack.github.io"
theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /blog/:title/


