title: Arian Designs
description: "Clean, modern, and minimal design"
baseurl: "" 
url: "https://ariantechzone-stack.github.io" 

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap






