title: "Arian Designs"
description: "Modern Clean Blog + Portfolio"
baseurl: ""
url: "https://ariantechzone-stack.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /blog/:title/

